In [3]:
import numpy as np
print(range(10))     # type range
print(np.arange(10)) #type numpy.ndarray

range(0, 10)
[0 1 2 3 4 5 6 7 8 9]


In [8]:
np.arange(1. , 3).dtype

dtype('float64')

In [10]:
a = np.arange(1,100,2)
# 논항을 사용 변수에 넣어야함
a.reshape(10,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [14]:
# 앞에 변수에 저장됌 치환문을 사용
a.shape = (5,10)
a

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29, 31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49, 51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69, 71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89, 91, 93, 95, 97, 99]])

In [16]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
a = a + [1,2,3]
a

array([[ 3,  6,  9],
       [ 6,  9, 12]])

### 연습문제 1 코드 작성

In [21]:
a = np.arange(1.5,12,2)
a

array([ 1.5,  3.5,  5.5,  7.5,  9.5, 11.5])

In [26]:
# dtype str도 가능
b = np.arange(1.5,12,2).reshape(2,3).astype(dtype='U')
b

array([['1.5', '3.5', '5.5'],
       ['7.5', '9.5', '11.5']], dtype='<U32')

In [29]:
c = (np.arange(1.5,12,2) * 2).reshape(3,2).astype(dtype='i')
c

array([[ 3,  7],
       [11, 15],
       [19, 23]], dtype=int32)

In [36]:
# 인덱싱과 슬라이싱 : 1차원
a = np.arange(1,7)
print(a)
print(a[5])
print(a[2:4])
a[5] = 12
print(a)
a[1:3] = [14,13]
print(a)
a[1:3] = 12
print(a)
a[1:3] = [14]
print(a)

[1 2 3 4 5 6]
6
[3 4]
[ 1  2  3  4  5 12]
[ 1 14 13  4  5 12]
[ 1 12 12  4  5 12]
[ 1 14 14  4  5 12]


In [45]:
# step : 1차원
a = np.arange(1,10,2)
print(a)
print(a[::])
print(a[::2])
print(a[2::2])
print(a[::-1])
print(a[::-2])
print(a[-2::-1]) #인덱스 -2의 값이 7
print(a[2::-1]) #인덱스 2 의 값이 5

[1 3 5 7 9]
[1 3 5 7 9]
[1 5 9]
[5 9]
[9 7 5 3 1]
[9 5 1]
[7 5 3 1]
[5 3 1]


In [56]:
# 인덱싱과 슬라이싱 : 2차원
a = np.arange(1,13).reshape(3,4)
print(a)
print('----------------')
print(a[-1])
print(a[0][-1])
print(a[-1][0])
print(a[0:2])
print(a[0:1])      # 2차원
print('----------------')
print(a[0:2][0])  # 차원이 줄어듬 ( 1차원 )
print(a[0:2][0][1:]) #1차원의 슬라이싱

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
----------------
[ 9 10 11 12]
4
9
[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]]
----------------
[1 2 3 4]
[2 3 4]


In [64]:
# step : 2차원
print(a)
print('----------------')
print(a[::2])
print(a[::-1])
print(a[1::-1])
print('----------------')
print(a[::2][1])
print(a[::2][1:2])
print(a[::2][::2]) # 인덱스 2가없기에 0만 출력되지만 2차원

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
----------------
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[[5 6 7 8]
 [1 2 3 4]]
----------------
[ 9 10 11 12]
[[ 9 10 11 12]]
[[1 2 3 4]]


In [74]:
# 행과 열 : 인덱싱, 슬라이싱
print(a[0][1])
print(a[0,1])

print(a[0:2][1])
print(a[0:2,1])

print(a[:][:-1])
print(a[:,:-1])
print(a[0,])

2
2
[5 6 7 8]
[2 6]
[[1 2 3 4]
 [5 6 7 8]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
[1 2 3 4]


### 연습문제 2 코드 완성

In [76]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [82]:
a[:2,1:]

array([[2, 3, 4],
       [6, 7, 8]])

In [84]:
a[2]

array([ 9, 10, 11, 12])

In [86]:
a[2,]

array([ 9, 10, 11, 12])

In [88]:
a[2:,] # 2차원으로 출력

array([[ 9, 10, 11, 12]])

In [91]:
a[:3,:2]   # a[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [93]:
a[1,:2]

array([5, 6])

In [103]:
a[1:2,:2]

array([[5, 6]])